In [1]:
In[1]: import numpy numpy.__version__
Out[1]: '1.11.1'

SyntaxError: invalid syntax (1893652830.py, line 1)

In [2]:
def my_name(name):
    print("i am " + name)  
my_name("cele")

i am cele


In [2]:
l=list(range(10))
print(l)
type(l[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


int

In [13]:

l2=[str(c) for c in l]
print(l2)
type(l2[0])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

In [19]:
l3=["cele","c",3.5,3,True]
[type(item) for item  in l3]



[str, str, float, int, bool]

In [31]:

L = list(range(10)) 
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
l=list(range(20))
a=array.array('i',l)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
import numpy as np
np.array([1,2,2.3,4,5])

In [ ]:
import numpy as np
np.array([1, 2, 3, 4], dtype='float32')

In [ ]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])

In [4]:
import numpy as np
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
import numpy as np
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
result = 0 
for i in range(100): 
    result+=i
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [18]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5),3.5)

array([[3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.random.random((3,3))

array([[0.4153348 , 0.83599557, 0.19063647],
       [0.26293566, 0.69046936, 0.51833226],
       [0.82354914, 0.25203958, 0.11167941]])

In [26]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [6]:
import numpy as np
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(::5)

In [ ]:
x=([1,2,34,]
   [9,7,8]
  [4,2,9])
x_sub = x[:2, :2] 
print(x_sub)